spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: ${DB_URL:jdbc:h2:file:./accounting-h2-database}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.default_schema: public
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
